// NOTE: this file is auto-generated by Construct
declare namespace InstanceType {
	class Keyboard extends IInstance {
	}
	class Mouse extends IInstance {
	}
	class Web extends IInstance {
	}
	class __BallBehaviors<InstType> {
		平台: IPlatformBehaviorInstance<InstType>;
		镜头跟随: IBehaviorInstance<InstType>;
	}
	class Ball extends ISpriteInstance {
		behaviors: __BallBehaviors<this>;
	}
	class __BallRopeBehaviors<InstType> {
		正弦运动: ISineBehaviorInstance<InstType>;
	}
	class BallRope extends ISpriteInstance {
		behaviors: __BallRopeBehaviors<this>;
	}
	class Door extends ISpriteInstance {
	}
	class __GroundBehaviors<InstType> {
		Solid: ISolidBehaviorInstance<InstType>;
	}
	class Ground extends ISpriteInstance {
		behaviors: __GroundBehaviors<this>;
	}
	class Spikes extends ISpriteInstance {
	}
	class __SpringBehaviors<InstType> {
		实体: ISolidBehaviorInstance<InstType>;
	}
	class Spring extends ISpriteInstance {
		behaviors: __SpringBehaviors<this>;
	}

}