// NOTE: this file is auto-generated by Construct
declare class IConstructProjectObjects {
	readonly Keyboard: IKeyboardObjectType<InstanceType.Keyboard>;
	readonly Mouse: IMouseObjectType<InstanceType.Mouse>;
	readonly Web: IObjectType<InstanceType.Web>;
	readonly Ball: IObjectType<InstanceType.Ball>;
	readonly BallRope: IObjectType<InstanceType.BallRope>;
	readonly Door: IObjectType<InstanceType.Door>;
	readonly Ground: IObjectType<InstanceType.Ground>;
	readonly Spikes: IObjectType<InstanceType.Spikes>;
	readonly Spring: IObjectType<InstanceType.Spring>;
}